src/Entity/Goods.php
<?php

namespace App\Entity;

use App\Repository\GoodsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GoodsRepository::class)]
class Goods
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $good_name = null;

    #[ORM\Column]
    private ?int $cost = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Shops $shop_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGoodName(): ?string
    {
        return $this->good_name;
    }

    public function setGoodName(string $good_name): static
    {
        $this->good_name = $good_name;

        return $this;
    }

    public function getCost(): ?int
    {
        return $this->cost;
    }

    public function setCost(int $cost): static
    {
        $this->cost = $cost;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getShopId(): ?Shops
    {
        return $this->shop_id;
    }

    public function setShopId(?Shops $shop_id): static
    {
        $this->shop_id = $shop_id;

        return $this;
    }
}

src/Entity/Shops.php
<?php

namespace App\Entity;

use App\Repository\ShopsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ShopsRepository::class)]
class Shops
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $shop_name = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $owner_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getShopName(): ?string
    {
        return $this->shop_name;
    }

    public function setShopName(string $shop_name): static
    {
        $this->shop_name = $shop_name;

        return $this;
    }

    public function getOwnerId(): ?Users
    {
        return $this->owner_id;
    }

    public function setOwnerId(Users $owner_id): static
    {
        $this->owner_id = $owner_id;

        return $this;
    }

}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
class Users
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(length: 50)]
    private ?string $surname = null;

    #[ORM\Column(length: 60)]
    private ?string $login = null;

    #[ORM\Column(length: 60)]
    private ?string $password = null;

    #[ORM\Column]
    private ?bool $has_ability_for_shop = null;

    #[ORM\Column]
    private ?bool $admin_role = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): static
    {
        $this->surname = $surname;

        return $this;
    }

    public function getLogin(): ?string
    {
        return $this->login;
    }

    public function setLogin(string $login): static
    {
        $this->login = $login;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function isHasAbilityForShop(): ?bool
    {
        return $this->has_ability_for_shop;
    }

    public function setHasAbilityForShop(bool $has_ability_for_shop): static
    {
        $this->has_ability_for_shop = $has_ability_for_shop;

        return $this;
    }

    public function isAdminRole(): ?bool
    {
        return $this->admin_role;
    }

    public function setAdminRole(bool $admin_role): static
    {
        $this->admin_role = $admin_role;

        return $this;
    }
}

templates/account.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset("css/account.css") }}">
{% endblock %}
{% block body %}
        <table>
            <tr class="tr-head" style="z-index: 100">
                <td style="margin-right:900px;" class="unwrap">
                    <select class="chosen">
                        <option>Все магазины</option>
                        {% for shop in shopSel %}
                            <option class="shop-select" id="{{ shop.id }}">{{ shop.shopName }}</option>
                        {% endfor %}
                    </select>
                    <button class="select-confirm">Перейти</button>
                </td>
                <td class="main-name-project" style="margin-left: 0; position: fixed; font-family: MainFont,serif; font-size: 65px; color: #173f33">Овощебаза</td>
            </tr>
            <tr style="position: relative; display: flex; margin-top: 98px; margin-left: -22px">
                <td>
                    <div class="container-shop">
                        <!-- переделать под твиg -->
                        <div class="personal-info">
                            {{ user.surname }} {{ user.name }}
                        </div>
                    </div>
                    <form method="POST" >
                        <table class="login-inf">
                            <tr>
                                <td>
                                    <label class="desc-input" >Логин: </label>
                                    <input class="name-input" name="current-login" style="margin-bottom: 20px" value="{{ user.login }}">
                                    <input class="submitLog" style="margin-bottom: 20px" value="Изменить" type="submit" name="submitLogin"/>
                                </td>
                            </tr>
                            {% if user.hasAbilityForShop == true %}
                                <tr style="margin-top: 30px">
                                    <td style="max-width: 750px; padding: 20px; border-radius: 20px;background-color: rgba(27,148,72,0.31); ">
                                        <div class="shop-info">
                                            <label class="desc-input">Магазин: </label>
                                            {% if shopName is defined %}
                                                <input class="name-input" name="shop-name-inp" value="{{ shopName }}">
                                            {% else %}
                                                <input class="name-input" name="shop-name-inp" value="" placeholder="назовите магазин">
                                            {% endif %}

                                            <input class="submitLog" value="Изменить" type="submit" name="submitShopName"/>
                                        </div>
                                        <div class="shop-info">
                                            <table>
                                                <tr>
                                                    <td>
                                                        <label class="desc-input">Добавить товар? </label>
                                                        <input class="name-input" style="margin-top: 10px" name="good-name" placeholder="название">
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <input class="name-input" style="margin-top: 10px; margin-left: 260px" name="good-cost" placeholder="стоимость">
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <input class="name-input" style="margin-top: 10px; margin-left: 260px" name="good-pic" placeholder="ссылка на картинку">
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <input class="submitLog" style="margin-top: 10px; margin-left: 260px" value="Добавить" type="submit" name="submitNewGood"/>
                                                    </td>
                                                </tr>
                                            </table>

                                        </div>
                                    </td>
                                </tr>
                            {% else %}
                                <tr style="margin-top: 30px">
                                    <td>
                                        <label class="desc-input" >Ваша корзина:</label>
                                    </td>
                                </tr>
                                {% if goodsInBasket is defined %}
                                    <form method="post">
                                        {% for good in goodsInBasket %}
                                            {% if good is defined %}
                                                <tr>
                                                    <td>
                                                        <div class="single-good">
                                                            <img class="good-preview" src="{{ good.goodId.picture }}">
                                                            <label class="good-name" style="margin-right: 20px">{{ good.goodId.goodName }}</label>
                                                            <input class="good-input" style="width: 100px; margin-right: 10px" name="num-of-goods-{{ good.id }}" placeholder="кол-во" value="{{ good.number }}">
                                                            <label class="good-name" name="good-cost">{{ good.goodId.cost }}</label><label class="good-name">₽/кг</label>
                                                            <button class="add-to-basket" type="submit" name="add-to-basket-now-{{ good.id }}" id="{{ good.id }}">Изменить</button>
                                                        </div>
                                                    </td>
                                                </tr>
                                            {%  endif %}
                                        {% endfor %}
                                        <tr>
                                            <td>
                                                <input class="submitLog" style="margin-top: 10px; margin-left: 260px" value="Заказать" type="submit" name="submitNewOrder"/>
                                            </td>
                                        </tr>
                                    </form>
                                {% endif %}
                            {% endif %}
                        </table>
                    </form>

                </td>
            </tr>
        </table>
    </div>
    <script type="module" src="{{ asset("js/account.js") }}"></script>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Овощебаза{% endblock %}</title>
        <link rel="icon" href='https://cdn-icons-png.flaticon.com/512/5775/5775998.png'>
        {% block stylesheets %}
        {% endblock %}
        {% block javascripts %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/exception.html.twig
{% extends "base.html.twig" %}
{% block head %}
    <link rel="stylesheet">
{% endblock %}
{% block body %}
    <div class="content" style=" justify-content: center; text-align: center; margin-top: 10%;">
        <label style="font-family: 'Arial Black'; font-size: 60px; color: #21310e;">
            Упс! Что-то пошло не так.
            <br>Причина: {{ exception }}
        </label>
        <img style="max-height: 70px" src="{{ asset('imgs/image_2023-12-09_22-30-51.png') }}">
    </div>
{% endblock %}

templates/index.html.twig
{% extends "base.html.twig" %}
{% block head %}
    <link rel="stylesheet" href="styles.css">
{% endblock %}
{% block body %}
    <div class="header">SMTH YEAR</div>
    <div class="content">
        
    </div>
{% endblock %}

templates/indexMain.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset("css/mainPage.css") }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.full.min.js" integrity="sha512-RtZU3AyMVArmHLiW0suEZ9McadTdegwbgtiQl5Qqo9kunkVg1ofwueXD8/8wv3Af8jkME3DDe3yLfR8HSJfT2g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}
{% block body %}
    <div class="container">
        <table>
            <tr class="tr-head">
                <td style="margin-right:900px;" class="unwrap">
                    <select class="chosen">
                        <option>Все магазины</option>
                        {% for shop in shops %}
                            <option class="shop-select" id="{{ shop.id }}">{{ shop.shopName }}</option>
                        {% endfor %}
                    </select>
                    <button class="select-confirm">Перейти</button>
                </td>
                <td style="margin-left: 0; position: fixed; font-family: MainFont,serif; font-size: 65px; color: #173f33">Овощебаза</td>
                <td class="login-info">Личный кабинет</td>
            </tr>
            <tr style="position: relative; display: flex; margin-top: 98px; margin-left: -22px">
                <td>
                    <div class="container-add">
                        <input type="radio" name="position" checked />
                        <input type="radio" name="position" />
                        <input type="radio" name="position" />
                        <main id="carousel">
                            {% if shops is defined %}
                                {% for shop in shops %}
                                    <div class="item" id="{{ shop.id }}">
                                        <img style="max-height: 200px; margin-top: 40px" src="imgs/pngwing.com{{ shop.id }}.png">
                                        <label class="shop-title-name">{{ shop.shopName }}</label>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </main>

                    </div>
                </td>
            </tr>
        </table>
    </div>
    <script type="module" src="{{ asset("js/mainPage.js") }}"></script>
    <script type="module" src="{{ asset("js/ajaxShops.js") }}"></script>
{% endblock %}

templates/login.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset("css/login.css") }}">
{% endblock %}
{% block body %}
    <div style="margin-top: 50px">
        <form class="container" method="POST" action="/login" target="_self">
            <label class="title-name">Овощебаза</label>
            <label class="name-input input-desc">Введите свой логин</label>
            <input name="login" class="info-input" id="login">
            <label class="name-input input-desc">Введите свой пароль</label>
            <input name="password" class="info-input" type="password" id="password">
            <label class="name-input registration" id="registry">Ещё не зарегистрированы?</label>
            <input class="submitLog" value="Войти" type="submit" name="submit"/>

        </form>
    </div>
    <script type="module" src="{{ asset("js/login.js") }}"></script>
{% endblock %}

templates/registration.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset("css/registration.css") }}">
{% endblock %}
{% block body %}
    <div style="margin-top: 50px">
        <form class="container" method="post">
            <label class="title-name">Овощебаза</label>
            <label class="name-input input-desc">Введите своё имя</label>
            <input name="name" class="info-input" id="name">
            <label class="name-input input-desc">Введите свою фамилию</label>
            <input name="surname" class="info-input" id="surname">
            <label class="name-input input-desc">Введите свой логин</label>
            <input name="login" class="info-input" id="login">
            <label class="name-input input-desc">Введите свой пароль</label>
            <input name="password" class="info-input" id="password">
            <input class="submitReg" value="Зарегистрироваться" type="submit" name="submit" />
        </form>
    </div>
    <script type="module" src="{{ asset("js/registration.js") }}"></script>
{% endblock %}

templates/shop.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset("css/mainPage.css") }}">
    <link rel="stylesheet" href="{{ asset("css/shop.css") }}">
{% endblock %}
{% block body %}
    <div class="container">
        <table>
            <tr class="tr-head">
                <td style="margin-right:900px;" class="unwrap">
                    <select class="chosen">
                        <option>Все магазины</option>
                        {% for shopS in shopSel %}
                            <option class="shop-select" id="{{ shopS.id }}">{{ shopS.shopName }}</option>
                        {% endfor %}
                    </select>
                    <button class="select-confirm">Перейти</button>
                </td>
                <td class="main-name-project" style="margin-left: 0; position: fixed; font-family: MainFont,serif; font-size: 65px; color: #173f33">Овощебаза</td>
                <td class="login-info">Личный кабинет</td>
            </tr>
            <tr style="position: relative; display: flex; margin-top: 98px; margin-left: -22px">
                <td>
                    <div class="container-shop">
                        <!-- переделать под твиg -->
                        <div class="title-shop">
                            <img class="title-img" src="{{ asset("imgs/image_2023-12-09_22-30-51.png") }}">
                            <label class="title-name">{{ shop.shopName }}</label>
                        </div>
                        <form method="POST" class="goods-table">
                            {% for good in goods %}
                                <div class="single-good">
                                    <img class="good-preview" src="{{ good.picture }}">
                                    <label class="good-name" style="margin-right: 20px">{{ good.goodName }}</label>
                                    <input class="good-input" name="num-of-goods-{{ good.id }}" placeholder="кол-во">
                                    <label class="good-name" name="good-cost">{{ good.cost }}</label><label class="good-name">₽/кг</label>
                                    <button class="add-to-basket" type="submit" name="add-to-basket-now-{{ good.id }}" id="{{ good.id }}">Добавить</button>
                                </div>
                            {% endfor %}
                        </form>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <script type="module" src="{{ asset("js/shop.js") }}"></script>
{% endblock %}